spring:
  devtools:
    restart:
      enabled: ture
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  datasource:
    url: jdbc:h2:tcp://localhost/~/project;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none # 내가 가진 sql 테이블을 다 지우고 다시 생성
    properties:
      hibernate:
        #        show_sql: true
        format_sql: ture

logging:
  level:
    org.hibernate.SQL: debug # 하이버네이트 sql 로그를 디버그 모드로 / 생성하는 sql에 다 보임
    org.hibernate.type: trace

file:
  dir: C:/Img/first/imgFile/

